import type { Metadata } from "next";
import { Tektur } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

const tektur = Tektur({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CBV - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={tektur.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
